apiVersion: v1
data:
    APP_NAME: ENC[AES256_GCM,data:yvLJ73uz/nvNREae9kMLUsmLTOX+CrL2,iv:AdZxbDTNHohLl+BhbiKMTZ9UuqE3RRJiQZf2CPYE1Qo=,tag:5lG1HDGSXzz8pvrJLmKoyA==,type:str]
    CONFIG_PATH: ENC[AES256_GCM,data:JWQuC8KyfTHwQ+GNJg+i4g==,iv:2MjiJZX0BFj8lrE3Wisozx09HvXYqPr83PbI3g1s8KI=,tag:jyuOp4mUYXpXBQUNfk9UIA==,type:str]
    POSTGRES_DB_HOST: ENC[AES256_GCM,data:ROlHwXFa+lhzkCIKQzee4vn492g6sl2wckNclFsYoEQ63aG4sP1O6A==,iv:2HNGg4W3drsX+lUkNwkBArUgBMUxa4DrT/kHkkPDTpk=,tag:PqT0Ak7wVaWX3N9CUZUTLw==,type:str]
    POSTGRES_DB_NAME: ENC[AES256_GCM,data:fsF0mPtMG5E=,iv:rUumf7oVbF1UxSOooGva+66gTfVQIykGQeTo7sTc+po=,tag:rGuUcmGkcLQwMSyJhcxxIw==,type:str]
    POSTGRES_DB_PORT: ENC[AES256_GCM,data:cOIZoAexIaI=,iv:jK/RFwFyx9LzqrSuNmMFhVRWf7eGyAi8lyI1lmNLzE4=,tag:SMgDEx1Fq+lqNQ4z/IKYsw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:JATDwPD0GDQ9UJJXcIm7wfy+jAL2Zz49,iv:ynNOF6dg3SeVV43ZuJYzfIOpKZKCXD7PpEY9BV3euIc=,tag:OfFaWvlIFYZfwAd4CLgM9w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:cwMBZ4kv+0fFcXh/9aXo6g==,iv:l3RQ9qBVHtUOoey9NPzbOqtfXa74p+1hAep3Skocng0=,tag:rQrz5HuXDbRcXMx2B1h6eA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:EEa9U+kp+QkUMYe65en1op3dhf2EldZaVVdRJfrfiW8=,iv:Mkj5uAmyo1GGAtBz6Q6aN6NgmRcpnR26UerTvHFqiF8=,tag:rJ1B0kzIpfCKXsL6hnGSPA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:56/NCM21ugo=,iv:W+RaruYz6k3GHBCHLkgrGkz4iSWsGpjIrRKZSARh878=,tag:fqHG/YJ91KCc0so+SoBG9g==,type:str]
kind: Secret
metadata:
    name: authorizer-service-secret
    namespace: authorizer-service-dev
sops:
    age:
        - recipient: age1zepgztvuxsysncygjteppy7jsdglmalfvx48p4ten06ndaycfs3qsgt3m9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRytZc1hKT3RVS1pyVTVi
            NldsalQzYnoyOVRjL0dQSjRrb29lcitPNG5ZCmgwdlZjOHNWSU5NU0tBMnZlVUpF
            ckxOTXVXcHdoOGNta0poS1ZiYTh3QTQKLS0tIGFlMFpYdEV3MG43ZW5LWTN3YXk0
            SE83cklQNlN1VnJPMFQvK2s5Wkd6Zk0KmWQeX7z/xVQcP8ydKDdHSzZla7C2/QGS
            flbA7i7LO+9VsQnaVWaNczplydRuCTlmVen6+8P21szAMiGD+yRmBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T04:29:05Z"
    mac: ENC[AES256_GCM,data:XA82QjyPgWWzoHqJzf0V4HnvgwRYI7K/a5EqwoOzt1Gtd3bzJte2a6Mz+2H2FFz2IPMbZB38Miad6UCVc/uu7Y+N0BODiaAzj+iRQlQfq4gd9krpdbWHgTSh0EX33L85tr9EaAFSuOqn5iL57M81drVccoVNbAAndIP5qH+ivVc=,iv:ROAxKD/HsyYZkidLZSDAg9GoxZCIX2KA8/GdpXjOtzw=,tag:vGxo9xLSfZ/19pUr13c60g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
