apiVersion: v1
data:
    APP_NAME: ENC[AES256_GCM,data:17o3ItIakh2K9u6JiiOsFtXciakX06bH,iv:xBvwBRZGHotIFG0BhRn+MUrn8NcC5G0+qs0jRaMWMcQ=,tag:xNphqePQdF0hSONVfP7TRw==,type:str]
    CONFIG_PATH: ENC[AES256_GCM,data:CYJ3rIIMQDbAU8LMb9eGVA==,iv:NNIlfHfaEPCTvNrGJr88jHZLB7I/SFbw7VWylJE94/0=,tag:1KAQzHRgJFZNlurb3tJQJA==,type:str]
    POSTGRES_DB_HOST: ENC[AES256_GCM,data:D/v37wz9UPU+HsIVCgOx1XWaQH7b6Tu2ygyNinISlTVF9drFzXXjCA==,iv:4ogyvhGGG0U5Q8JB7HZFaZCLvuVXv22qslKzoKdqa1w=,tag:UhS/RXES2YEdblPfshS0fQ==,type:str]
    POSTGRES_DB_NAME: ENC[AES256_GCM,data:2wyTb28NmHI=,iv:irypTscJ2EjpC73yUyrsFvohSZHa+pXenuqT/IgagwE=,tag:XkrEscCC935T7MlqB52xfA==,type:str]
    POSTGRES_DB_PORT: ENC[AES256_GCM,data:8YAlkHyc4Pg=,iv:PCj7CPQJi2a5b3dfPMeJYIFLGwSHD0QYHbByXtyGBX8=,tag:A4GQGKbOJSg6M5bBaPxUAg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:sZ8yc0qUae3rTGlMD3rLY6SERIm/hkp8,iv:utrMdzWJCR/uAL9GLBVklL9uyR1YQC3g5lYL/OxVF1U=,tag:gWt5vZRsEIc6E2J5opaAww==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:LnyMjtBL4y7Xqk0PC6E+2g==,iv:TNAmrrBkNPgZifaxN6vugrLprIMRe7BA7OsMU7WrcDU=,tag:b89+BcqT1eITTwJpDDwI6A==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:xAMIa/PpPO8tZX3Yzu3X8g==,iv:ZRgiSHTHxQoBII2GFVzXr/pzlEBnxg0q6mYadtMcZQ0=,tag:fJmRoqmH7Td/kzM5h1jwtg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:azeIjw8LEb0=,iv:auICcMS35+micRsKW9e6bbM1Fg28y1BQlzoN4gThrnQ=,tag:6yUXNq2wfHEvVKxYCCRQXA==,type:str]
kind: Secret
metadata:
    name: authorizer-service-secret
    namespace: authorizer-service-dev
sops:
    age:
        - recipient: age1zepgztvuxsysncygjteppy7jsdglmalfvx48p4ten06ndaycfs3qsgt3m9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYWlmbGZ4Q3NlQ2kwek83
            RzJ2N3NLeU03bGRiZ0JhYTlHeVlHT0hDcUZJClYrbDdHeDVVVTcxa2JFNlgvVk1U
            bGdVZUNXaWNpR0pWYW5SSDFaUVdpSFEKLS0tIG5XaDVXazBNZ1pYWmgxMEF4Y3Yr
            emJ0ZUJuNzVIcEpzc1ZNb0dkTlhzQnMK0h55383RrBSyoHvGllsjRs01RpXIkSGR
            ouO/KAUI0UPh/H8ujUpHo/yUPMhDELbIHOYZK4iQLnmwQxn0at8Kew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T18:26:38Z"
    mac: ENC[AES256_GCM,data:E/fWVrL1Z2OsJhr85Ku8S+eNGPsGaP3t+ZTWNywXZCrACL1ZDAuv/GpftM4Vtq/Uqi8VHnaglT6+OUWJSL9AJX9ep1OJfrIGa/Zz6MDKe6GtnKOheG2TEzuEMdqTOdQ+YXlvzfCbUoEiJNHBNx9U2w59WugHfVpWRzzQv8AEkyU=,iv:i1tdrjypm1Bfd68WPEcmOUSrnI8BI/GTyYAHoN9qOQI=,tag:8mgpIKcPPlDyvQSouzphZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
