apiVersion: v1
data:
    APP_NAME: ENC[AES256_GCM,data:LqTxh8HWbr29/v+FBv+0afvWYWKAiYe9,iv:Qp/vyKU/8iM4whBs6CjWA4tkPHlAzKMFix4OxWGKB6k=,tag:GyoxzRPcKFHZ/5L24wD+Ug==,type:str]
    CONFIG_PATH: ENC[AES256_GCM,data:yZD/DJDVL7mjIE2iWduMbA==,iv:mPC3nYtbTM5aR8HVZoNvcIVdF4mCIvHE10YhEcCgNaA=,tag:2jpsRqm5Vs0QRHJOaPDY3w==,type:str]
    JWT_PRIVATE_KEY_PATH: ENC[AES256_GCM,data:mXKRa/IkHaNNcbzlRiwKDk7CapUOrrzk,iv:T9M07bq0u6K35uLjnOFRdCROx3rSnIUnun1pOf3AMdg=,tag:RENPHoE79N2Fq4/QRiBIyQ==,type:str]
    POSTGRES_DB_HOST: ENC[AES256_GCM,data:5Wqi7Ex9lguQROxQoEFcHeOHof31ZqZNRK8qkeK6iHEbcmnNbKsPKg==,iv:BgWiqiPtfEko4zj13bTVHXgOv9e0O9uAG30uLfDgicg=,tag:QIf1gtc5dUMV4VKhD2gvcA==,type:str]
    POSTGRES_DB_NAME: ENC[AES256_GCM,data:ipFl11/0vOs=,iv:wAL8/AED8VpxrT9X2+/bpeR70Jnc3+jn17UdpafJmV8=,tag:JoSRFE15Nf49V7gQpiPFOQ==,type:str]
    POSTGRES_DB_PORT: ENC[AES256_GCM,data:q0OvJhPgwyk=,iv:4K2mBWgo+0+daWmCBQXREr3dHd54lk6eXwIWun/kTzI=,tag:ceM3MfRIV9axFiI+smUq9g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:oIa2UolwqjVxcmW45p90MC7dtnlmSE97,iv:BREVSvpPGAFCggm7RzX0w8VaRvCuc++DqHB5PYYbbZQ=,tag:hVvfLD/3/SsdKuiTfrjwSg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:++jOYFAg7aiNFU5se1xmUA==,iv:riTS36wL1Na4hrlMgjiz2qnZKEARXu3neXeJ634URZ0=,tag:MNm9x3W/UI5BTO9pGT3OgQ==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:l7zQHYuhrIikqMUIlabrLiRyRkZDOCO6dmQp4U9GNX0=,iv:w2hUuWHl7dAegvP3Ekyyv1Wj7imgO2F2KTLlq0Q/Kk8=,tag:+yf8SOBVIYd2+JfmTVjDiQ==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:NIs3eFPzyj4=,iv:bKFjz0kn4vJKOYEJWHUdySwciVkN4FBT0cj3vvHYOAw=,tag:G3NAMGKIroDdrrenO5E56g==,type:str]
kind: Secret
metadata:
    name: authorizer-secret
    namespace: authorizer-dev
sops:
    age:
        - recipient: age1zepgztvuxsysncygjteppy7jsdglmalfvx48p4ten06ndaycfs3qsgt3m9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueG5tN2szVlhTVjFXb1NE
            c2d5bTdHZjZrTzNvbnVrUTVmNXJxL0RWTGlnCkgrQ2h2Z0RxRWVMWmJ5bzM2eVdy
            MUtmNnFmTjRVL2tYck96STFBbEsxd2cKLS0tIFl2S3RYMjBRUWV4MEMyQmV0NFAr
            R2NGaWlmQzFFZ0w2Sks3eG9Ua2pQc00KZm6gm3gsW+iIbL0ihpvyhoIXFq8Fh0eU
            H5bTH1Ld9Ur2WtWPkhOIrmCY5bsYLB/TBaCJQtMyRmuHqKw/8EAkQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T15:52:24Z"
    mac: ENC[AES256_GCM,data:e+yS3QjsU20d9mHf9sS0DHyr9JwT1kLtlzhGGbUSMSjtUtb6fVPCysbNeR3tBEPDYMPcj6FoLMJl/51atiI/EhKRJ0SvrMBSQm+yRv2kO1DJvLgiKVRLplQz3ynJ+fb8XGNO/byz0/+7ABFo00mvWowfit7EMlYRZeovjsGslyk=,iv:3XazwHpfGni9ucyIvSAi0jYHbvCYxS74O3S8Ub+zwOg=,tag:DmD5UbiXs74OmO/glC6GAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
