apiVersion: v1
data:
    APP_NAME: ENC[AES256_GCM,data:TgaXsi8M/WHPJxv+ovuyLw==,iv:DoLMR+TVv+kR9QaeV2hnr2mEku0yOheN0PWk/4pLlZA=,tag:jVt7s7Wave3Q+dQDb2XtpA==,type:str]
    CONFIG_PATH: ENC[AES256_GCM,data:qOTVU5wq6zYAxQV596VlPw==,iv:8eihAblHFWSzPfAEOM+l3uzO3VNT5y1/jILrjkNsyGM=,tag:EgqvSuOl93YYrWqUXHnJzg==,type:str]
    JWT_PRIVATE_KEY_PATH: ENC[AES256_GCM,data:7dxJiVCFdZhlAH0lgXEPijCv74khW8I9,iv:ozGY/gJx7XxB9l1vDhUrRyLFVja+U66kZt6FAPd1C+g=,tag:XIf+TXvFp61XrYn82nyzsw==,type:str]
    POSTGRES_DB_HOST: ENC[AES256_GCM,data:mkaQqRmHGf1XE6Vv8gQYyDKRfTrkVEstmGKmxA88g4rOdKuuX7YFwA==,iv:6X71mHr498455jD63OmZ3H9cNI3Kjd+WbhyGoKP8cN0=,tag:Mff+GIcuNVIytDl4ffEpgQ==,type:str]
    POSTGRES_DB_NAME: ENC[AES256_GCM,data:x8j19WJiJhM=,iv:Knhqy/Z1HXMjdtTXUcUs6Jm+DySAPpAhLPpf7wPp30c=,tag:ILp3yzjEGu8cce7lt7Z7tg==,type:str]
    POSTGRES_DB_PORT: ENC[AES256_GCM,data:z9ojU33G5Yo=,iv:P6+jkaNLqVwMt70wI/bw82RW+zQqMzMQu3IN4ZJ7tLw=,tag:ZlLb/INPizbGhTwgR9XVEA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:aGPg7utLb+ZdFzKrUJI6cfcwKjNQlth/,iv:3ig2R5xrIiYdIDDJOFcs4l114OyXBWIEgpZpYJNAd7Q=,tag:/IuJOzFf5Yqd/xDKn8dCBQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:jshCTSnmbhAyRUXITjPu1w==,iv:E/J5+qvhhVW+oiXp81nfb5rQCwISWWnzIOSiCevhln8=,tag:JUV2iLrJLOCYvYvHSjE6IA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:uvV6P+H8leZc4YYxmjZQb7SJycZh4uqPxPvPcqFNQMY=,iv:mK5T10olFnIzW25ya9oQxhfGB53oHTo23lki96N1bGE=,tag:IPKLQGNt9i003E7EI7roaw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:jZjmm/wMkjQ=,iv:LRhaLeftO30X4pmz/J5NQAQQtWsnRgbR4u8EEoHACuM=,tag:fRCmqUf+XRJ0I7CLVSuhYg==,type:str]
kind: Secret
metadata:
    name: authorizer-secret
    namespace: authorizer-production
sops:
    age:
        - recipient: age1zepgztvuxsysncygjteppy7jsdglmalfvx48p4ten06ndaycfs3qsgt3m9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUkZLS29ZTXkwcXArNGYx
            cWordWtlRTd1YXhqYm1SajExd1VkeUhRSUFjCnF1c3graVQwMUNUM2VWaHJoeXpx
            UldOZWVTbUF0ZnU4OHN6TlRra3lZencKLS0tIHR6eVlDODBDUnZyUlZtNHB5WEk4
            aWtjRWVzdEY4T3BuK2t5K2MvZno4UDgKMPFUoo3K9V6fMzEKMFXhBtRuS+3I0M0p
            N3gTDyDjaSoE+inbfX5ZGAsXmg6NaxKDARxiEjXOquNWklCHvDsTHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T13:52:16Z"
    mac: ENC[AES256_GCM,data:12hV7Xv/Wbpx9IoLPPwhGjb9GMmpHsXKYQ9UiGN2zM/nvyZbyrnAQtl+VRGrRS/k0l/9eRPC2bmInjDyt6LPLaMZIvwkfphr5L2oNaTn3J6ln133ZtSvCqNNNJ/cgufs7TSM2f7CFlaOJ5YMtg0DL4i9/jG1b4EGCe7j4fCxa9Q=,iv:FvWkX0JET2JX5xYlt9IoKhm/M0VCHxikUM1JEQPx40w=,tag:o3DDRA7gAAFctlqkcpgVPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
