apiVersion: v1
data:
    APP_NAME: ENC[AES256_GCM,data:RqfaF+0/IRp22q9vl8q3Jw==,iv:UYzR/4fnieri2pv1qQuBML0WHs3drGZ0iOUU3qvwI1c=,tag:n6RUkp6sBJTQ9gVqERT5jg==,type:str]
    CONFIG_PATH: ENC[AES256_GCM,data:X7W1/Stx4zGvG4PHiVQPDg==,iv:9gG0ocqqs6lKbB1SbZwUwlGj87MOCmud4BJ/c9TaipM=,tag:xi3m2tzmAv++txSIQYtK8g==,type:str]
    JWT_PRIVATE_KEY_PATH: ENC[AES256_GCM,data:DLCeLsYE5CRqRgMDe6V1v7FlIZd7PoKV,iv:bSRQL/SIqQedxSkGtjM00UMu1vV0xCc2oobghe6xMw4=,tag:yrrvN2AiRga9+dlWs4iGyg==,type:str]
    POSTGRES_DB_HOST: ENC[AES256_GCM,data:rXsTSilMIDet0qbmNL//k6vaozoLKIanWAl9s/DH02ebvOqJbEcQNA==,iv:7zWyy0ohISDYvcOAs04yvM5yuV9F+zBxiBfo5DEsbGQ=,tag:ZZ6aqHvlMRNEwsPc9s0jZw==,type:str]
    POSTGRES_DB_NAME: ENC[AES256_GCM,data:MMEHGafCOyk=,iv:QDRTnb6DIpuqsBsP+e86OIAMPNhVbAndEz4je2w0zm8=,tag:sRYMPFCoG0RdqYnGx+RTgQ==,type:str]
    POSTGRES_DB_PORT: ENC[AES256_GCM,data:D0QrB6nET7w=,iv:xyerloJ0jsw84aR5DkhVBUG2iYsZWSUk6zel2bhCGdw=,tag:EhmV0wQ8MkyL12HsFmK/IA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:MTEGsBlU17gI6RWYrsOHVInG1cb5x0yJ,iv:y+wuB3ffpwAqSLPk6cvGN2j2JDQDmccL3KxMd0XJ1mc=,tag:eimPxGXFp7JPZZVIxIEwTA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:inx6esG8o5d9KBLQ6B6DMg==,iv:iJ0Z/JFZsnMatEc0iu8VcGtPiVeHhBtS6V48zcoUmeo=,tag:C3Be3XFKZqw9CKzyw67k3w==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:PaKj9AAkYPblAGArvmeTT6M3CVLjmNPQW2MDQ+aS5kA=,iv:CLJGq++AT6E4O9T04WZ27zgmKmcXNCpcPFvnOUf/LtY=,tag:RGDKyH3C5FpXNVa0sBPJsA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:gkcs6poOWBk=,iv:Kmg5t4bRHVMqs9B0D+6f+OK5SH3t06ezNqvcpQeVZOo=,tag:+jgPEOdC55Vi4Wnd7cZyIw==,type:str]
kind: Secret
metadata:
    name: authorizer-secret
    namespace: authorizer-dev
sops:
    age:
        - recipient: age1zepgztvuxsysncygjteppy7jsdglmalfvx48p4ten06ndaycfs3qsgt3m9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOGRuSW1TcGU1Rkt6MkFC
            aWJ2NFgrY2JOcDR6b2lWMXAza05ERTlsQmdjCmVLVDBEYmhtaklVbTV3alRidE93
            ZmVPaVlseDQvZHBKWHFtQXRmcm50Ym8KLS0tIGxkUjV6Y0dDS3NaR1VCekFhRjhV
            Ynd3a1hpcjlua0JPaXkrN2FQUFN6MzgKuWJ0uEkY5YrfBxwtHHuFfXZe2pW7Im75
            eBeUnicnLJB/FOJUTwlzh4l/zFZej+ru8p7i/bxD1oZXu6EQnuH85w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T14:20:06Z"
    mac: ENC[AES256_GCM,data:yw0xlfraCKlADwOLKCCIK5FsjIpvMFabJ2o2PDM3dYrF+Cji9EdaJIdztF/95aWZJha1eYKgSilYtaorLNnsu/93l8vimKY2Mri7CdPfpmBI1mFm2uImBvliFaSjLfihzrzK9xf+ePa3bbewJJeww/3GYQWtxINgsyIKC+rkKdw=,iv:mJQZhkusXnDM1g++TAiibapejctw4tQDflutulWpswQ=,tag:/hf5Iraw25DHAK/DAamVbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
